# Generated by Django 5.1.6 on 2025-02-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=494)),
                ('mtm', models.ManyToManyField(related_name='Customer', to='booking.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=494)),
                ('mtm', models.ManyToManyField(related_name='Apartment', to='booking.landlord')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='mtm',
            field=models.ManyToManyField(related_name='Customer', to='booking.landlord'),
        ),
    ]
