# Generated by Django 5.1.6 on 2025-03-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_landlord_customer_apartment_mtm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name': 'owner'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='mtm',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mtm',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='mtm',
        ),
        migrations.AddField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.landlord'),
        ),
    ]
